export const ADMIN_DASHBOARD_JS = `
let token = "";
let page = 1;
let pageSize = 50;
let selectedIds = new Set();
let currentEmails = [];
let rules = [];
let rulePage = 1;
const rulePageSize = 8;
let selectedEmailId = "";
let searchTimer = null;

const $ = id => document.getElementById(id);
const ICONS = {
  eye:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.5"/></svg>',
  trash:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13M10 11v5M14 11v5"/></svg>',
  lock:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg>',
  unlock:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 7-2.5"/></svg>',
  rule:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M5 4h14v16H5z"/><path d="M8 8h8M8 12h8M8 16h5"/></svg>'
};

function notice(text,type){const e=$("globalMessage");e.textContent=String(text||"");e.className="notice show "+(type||"ok");setTimeout(()=>e.className="notice",4200)}
function loginNotice(text){const e=$("loginMessage");e.textContent=String(text||"");e.className="notice show error"}
function escapeHtml(v){return String(v==null?"":v).split("&").join("&amp;").split("<").join("&lt;").split(">").join("&gt;").split('"').join("&quot;").split("'").join("&#039;")}
function date(v){const n=Number(v);if(!Number.isFinite(n))return String(v||"-");const d=new Date(n<100000000000?n*1000:n);return Number.isNaN(d.getTime())?String(v||"-"):d.toLocaleString()}
function relative(v){const n=Number(v);if(!Number.isFinite(n))return date(v);const ms=n<100000000000?n*1000:n,diff=Math.max(0,Date.now()-ms),m=60000,h=3600000,d=86400000;if(diff<m)return"Just now";if(diff<h)return Math.floor(diff/m)+" min ago";if(diff<d)return Math.floor(diff/h)+" hr ago";if(diff<d*7)return Math.floor(diff/d)+" d ago";return new Date(ms).toLocaleDateString()}
async function api(path,options){const o=options||{},r=await fetch(path,Object.assign({},o,{headers:Object.assign({Authorization:"Bearer "+token},o.headers||{})}));let data=null;try{data=await r.json()}catch(_){}if(r.status===401){logout();throw new Error("Unauthorized")}if(!r.ok)throw new Error(data&&data.error&&data.error.message||"Request failed");return data}
function login(){const v=$("tokenInput").value.trim();if(!v)return loginNotice("Please enter the admin token.");token=v;api("/admin/api/emails?page=1&pageSize=1").then(()=>{$("loginScreen").classList.add("hidden");$("app").classList.remove("hidden");refreshAll()}).catch(e=>{token="";loginNotice(e.message||"Invalid admin token.")})}
function logout(){token="";selectedIds.clear();$("app").classList.add("hidden");$("loginScreen").classList.remove("hidden");$("tokenInput").value=""}
function action(icon,title,cls,fn){const b=document.createElement("button");b.className="icon-btn "+(cls||"");b.title=title;b.setAttribute("aria-label",title);b.innerHTML=icon;b.onclick=fn;return b}
function selectionUi(){const n=selectedIds.size;$("selectionBar").classList.toggle("hidden",n===0);$("selectionCount").textContent=n+(n===1?" email selected":" emails selected");$("selectAll").checked=currentEmails.length>0&&currentEmails.every(e=>selectedIds.has(String(e.id)))}
function renderRow(e){const row=document.createElement("tr");const c=document.createElement("td"),cb=document.createElement("input");cb.type="checkbox";cb.className="checkbox";cb.checked=selectedIds.has(String(e.id));cb.onchange=()=>{cb.checked?selectedIds.add(String(e.id)):selectedIds.delete(String(e.id));selectionUi()};c.appendChild(cb);row.appendChild(c);[["from_address","address"],["to_address","address"],["subject","subject"]].forEach(([key,cls])=>{const x=document.createElement("td");x.className=cls;x.textContent=String(e[key]||"(No subject)");x.title=x.textContent;row.appendChild(x)});const dt=document.createElement("td");dt.innerHTML='<div class="date-main">'+escapeHtml(relative(e.received_at))+'</div><div class="date-sub">'+escapeHtml(date(e.received_at))+'</div>';row.appendChild(dt);const vis=document.createElement("td");vis.innerHTML=e.is_public?'<span class="badge public"><span class="dot"></span>PUBLIC</span>':'<span class="badge private"><span class="dot"></span>PRIVATE</span>';row.appendChild(vis);const ac=document.createElement("td"),box=document.createElement("div");box.className="row-actions";box.appendChild(action(ICONS.eye,"Read email","",()=>openEmail(e.id)));if(e.is_public)box.appendChild(action(ICONS.lock,"Make private","warning",()=>visibility(e.id,false)));else{box.appendChild(action(ICONS.unlock,"Make public","success",()=>visibility(e.id,true)));box.appendChild(action(ICONS.rule,"Make public and create future rule","",()=>openRuleModal(e.id,e.from_address,e.to_address,e.subject)))}box.appendChild(action(ICONS.trash,"Delete email","danger",()=>deleteOne(e.id)));ac.appendChild(box);row.appendChild(ac);return row}
function renderMobile(e){const box=document.createElement("div");box.className="mobile-email";const top=document.createElement("div");top.className="mobile-top";const cb=document.createElement("input");cb.type="checkbox";cb.className="checkbox";cb.checked=selectedIds.has(String(e.id));cb.onchange=()=>{cb.checked?selectedIds.add(String(e.id)):selectedIds.delete(String(e.id));selectionUi()};top.appendChild(cb);const badge=document.createElement("span");badge.className=e.is_public?"badge public":"badge private";badge.innerHTML='<span class="dot"></span>'+(e.is_public?"PUBLIC":"PRIVATE");top.appendChild(badge);box.appendChild(top);const s=document.createElement("div");s.className="mobile-subject";s.textContent=String(e.subject||"(No subject)");box.appendChild(s);["from_address","to_address"].forEach(k=>{const x=document.createElement("div");x.className="mobile-line";x.textContent=(k==="from_address"?"From: ":"To: ")+String(e[k]||"-");box.appendChild(x)});const dt=document.createElement("div");dt.className="mobile-line";dt.textContent=relative(e.received_at)+" · "+date(e.received_at);box.appendChild(dt);const a=document.createElement("div");a.className="mobile-actions";a.appendChild(action(ICONS.eye,"Read email","",()=>openEmail(e.id)));a.appendChild(action(ICONS.trash,"Delete email","danger",()=>deleteOne(e.id)));box.appendChild(a);return box}
function pagination(total){const pages=Math.max(1,Math.ceil(total/pageSize));$("pageInfo").textContent=total?"Showing "+((page-1)*pageSize+1)+"–"+Math.min(page*pageSize,total)+" of "+total:"No emails found";$("prevPage").disabled=page<=1;$("nextPage").disabled=page>=pages;const p=$("pageNumbers");p.innerHTML="";for(let n=Math.max(1,page-2);n<=Math.min(pages,page+2);n++){const b=document.createElement("button");b.className="page-btn"+(n===page?" active":"");b.textContent=n;b.onclick=()=>{page=n;loadEmails()};p.appendChild(b)}}
async function loadEmails(){const q=new URLSearchParams({page:String(page),pageSize:String(pageSize),visibility:$("visibilityFilter").value});const s=$("emailSearch").value.trim();if(s)q.set("search",s);const d=await api("/admin/api/emails?"+q);currentEmails=d.items||[];$("totalCount").textContent=d.total||0;$("publicCount").textContent=d.publicCount||0;$("privateCount").textContent=d.privateCount||0;const body=$("emailsBody"),mobile=$("mobileList");body.innerHTML="";mobile.innerHTML="";if(!currentEmails.length){body.innerHTML='<tr><td colspan="7" class="empty">No emails match your search.</td></tr>';mobile.innerHTML='<div class="empty">No emails match your search.</div>'}else currentEmails.forEach(e=>{body.appendChild(renderRow(e));mobile.appendChild(renderMobile(e))});pagination(Number(d.total||0));selectionUi()}
async function loadRules(){const d=await api("/admin/rules");rules=(d&&d.data)||d||[];rulePage=1;renderRules();$("ruleCount").textContent=rules.length+" rule"+(rules.length===1?"":"s")}
function renderRules(){const term=$("ruleSearch").value.trim().toLowerCase(),f=rules.filter(r=>(String(r.sender_pattern||"")+" "+String(r.recipient_pattern||"")+" "+String(r.subject_pattern||"")).toLowerCase().includes(term)),pages=Math.max(1,Math.ceil(f.length/rulePageSize));if(rulePage>pages)rulePage=pages;const start=(rulePage-1)*rulePageSize,list=$("rulesList");list.innerHTML="";f.slice(start,start+rulePageSize).forEach(r=>{const item=document.createElement("div");item.className="rule-item";const summary=document.createElement("div");summary.className="rule-summary";summary.innerHTML='<div><div class="rule-label">Sender</div><div class="rule-value">'+escapeHtml(r.sender_pattern||"All senders")+'</div></div><div><div class="rule-label">Recipient</div><div class="rule-value">'+escapeHtml(r.recipient_pattern||"All mailboxes")+'</div></div><div><div class="rule-label">Subject contains</div><div class="rule-value">'+escapeHtml(r.subject_pattern||"")+'</div></div>';const a=document.createElement("div");a.className="rule-actions";a.appendChild(action(ICONS.trash,"Delete rule","danger",()=>deleteRule(r.id)));summary.appendChild(a);item.appendChild(summary);list.appendChild(item)});if(!f.length)list.innerHTML='<div class="empty">No automatic rules found.</div>';$("rulePageInfo").textContent=f.length?"Showing "+(start+1)+"–"+Math.min(start+rulePageSize,f.length)+" of "+f.length:"No rules";$("rulePrev").disabled=rulePage<=1;$("ruleNext").disabled=rulePage>=pages}
async function openEmail(id){try{const d=await api("/admin/emails/"+encodeURIComponent(id)),e=d&&d.data||d;if(!e)throw new Error("Email not found");$("emailModalTitle").textContent=String(e.subject||"Email");const m=$("emailMeta");m.innerHTML="";[["From",e.from_address],["To",e.to_address],["Received",date(e.received_at)],["Attachments",String(e.attachment_count||0)]].forEach(p=>{const x=document.createElement("div");x.className="meta-item";x.innerHTML='<div class="meta-label">'+escapeHtml(p[0])+'</div><div class="meta-value">'+escapeHtml(p[1]||"")+'</div>';m.appendChild(x)});const c=$("emailContent");c.innerHTML="";if(e.html_content&&String(e.html_content).trim()){const f=document.createElement("iframe");f.className="email-viewer";f.sandbox="";f.referrerPolicy="no-referrer";f.srcdoc=String(e.html_content);c.appendChild(f)}else if(e.text_content&&String(e.text_content).trim()){const p=document.createElement("pre");p.className="email-text";p.textContent=String(e.text_content);c.appendChild(p)}else c.innerHTML='<div class="empty">No message content available.</div>';$("emailModal").classList.add("show")}catch(e){notice(e.message||"Failed to open email.","error")}}
function closeEmail(){$("emailModal").classList.remove("show");$("emailContent").innerHTML=""}
async function visibility(id,value){try{await api("/admin/emails/"+encodeURIComponent(id)+"/visibility",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({is_public:value})});notice(value?"Email is now public.":"Email is now private.");await loadEmails()}catch(e){notice(e.message,"error")}}
async function deleteOne(id){if(!confirm("Delete this email permanently?"))return;try{await api("/admin/emails/"+encodeURIComponent(id),{method:"DELETE"});selectedIds.delete(String(id));notice("Email deleted.");await loadEmails()}catch(e){notice(e.message,"error")}}
async function bulkDelete(){const ids=Array.from(selectedIds);if(!ids.length)return;if(!confirm("Delete "+ids.length+" selected email"+(ids.length===1?"":"s")+" permanently?"))return;const b=$("bulkDeleteBtn");b.disabled=true;try{const d=await api("/admin/api/emails/bulk",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids})});selectedIds.clear();notice((d.deleted||ids.length)+" email"+((d.deleted||ids.length)===1?"":"s")+" deleted.");await loadEmails()}catch(e){notice(e.message,"error")}finally{b.disabled=false}}
function openRuleModal(id,s,r,subject){selectedEmailId=String(id||"");$("modalSender").value=String(s||"");$("modalRecipient").value=String(r||"");$("modalSubject").value=String(subject||"");$("ruleModal").classList.add("show");$("modalSubject").focus()}
function closeRuleModal(){selectedEmailId="";$("ruleModal").classList.remove("show")}
async function confirmRule(){const s=$("modalSender").value.trim(),r=$("modalRecipient").value.trim(),subject=$("modalSubject").value.trim();if(!s||!r||!subject)return notice("Sender, recipient and subject phrase are required.","error");try{await visibility(selectedEmailId,true);await api("/admin/rules",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sender_pattern:s,recipient_pattern:r,subject_pattern:subject})});closeRuleModal();notice("Email is public and the future-matching rule was created.");await refreshAll()}catch(e){notice(e.message,"error")}}
async function addRule(){const s=$("newRuleSender").value.trim(),r=$("newRuleRecipient").value.trim(),subject=$("newRuleSubject").value.trim();if(!subject)return notice("Subject phrase is required.","error");try{await api("/admin/rules",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sender_pattern:s,recipient_pattern:r||null,subject_pattern:subject})});$("newRuleSender").value="";$("newRuleRecipient").value="";$("newRuleSubject").value="";notice("Automatic public rule added.");await loadRules()}catch(e){notice(e.message,"error")}}
async function deleteRule(id){if(!confirm("Delete this automatic public rule?"))return;try{await api("/admin/rules/"+encodeURIComponent(id),{method:"DELETE"});notice("Rule deleted.");await loadRules()}catch(e){notice(e.message,"error")}}
async function syncMailboxes(){const b=$("syncBtn"),s=$("syncStatus");b.disabled=true;b.textContent="Syncing...";s.textContent="Synchronizing mailbox accounts...";try{const d=await api("/admin/sync/mailboxes",{method:"POST"}),x=d&&d.result||d||{};notice("Mailbox sync completed successfully.");s.textContent="Sync completed: created "+(x.created||0)+", updated "+(x.updated||0)+", disabled "+(x.disabled||0)+", unchanged "+(x.unchanged||0)}catch(e){notice("Mailbox sync failed: "+e.message,"error");s.textContent="Sync failed."}finally{b.disabled=false;b.textContent="↻ Sync"}}
async function refreshAll(){try{await Promise.all([loadEmails(),loadRules()])}catch(e){notice(e.message,"error")}}

document.addEventListener("DOMContentLoaded",()=>{
$("loginBtn").onclick=login;$("tokenInput").onkeydown=e=>{if(e.key==="Enter")login()};$("logoutBtn").onclick=logout;$("refreshBtn").onclick=refreshAll;$("syncBtn").onclick=syncMailboxes;$("bulkDeleteBtn").onclick=bulkDelete;$("clearSelectionBtn").onclick=()=>{selectedIds.clear();loadEmails()};$("selectAll").onchange=e=>{currentEmails.forEach(x=>e.target.checked?selectedIds.add(String(x.id)):selectedIds.delete(String(x.id)));selectionUi();loadEmails()};$("visibilityFilter").onchange=()=>{page=1;loadEmails()};$("pageSize").onchange=()=>{page=1;pageSize=Number($("pageSize").value)||50;loadEmails()};$("emailSearch").oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{page=1;loadEmails()},300)};$("prevPage").onclick=()=>{if(page>1){page--;loadEmails()}};$("nextPage").onclick=()=>{page++;loadEmails()};$("ruleSearch").oninput=()=>{rulePage=1;renderRules()};$("rulePrev").onclick=()=>{if(rulePage>1){rulePage--;renderRules()}};$("ruleNext").onclick=()=>{rulePage++;renderRules()};$("addRuleBtn").onclick=addRule;$("confirmRuleBtn").onclick=confirmRule;$("cancelRuleBtn").onclick=closeRuleModal;$("cancelRuleBtnTop").onclick=closeRuleModal;$("closeEmailBtn").onclick=closeEmail;$("closeEmailBtn2").onclick=closeEmail;$("emailModal").onclick=e=>{if(e.target.id==="emailModal")closeEmail()};$("ruleModal").onclick=e=>{if(e.target.id==="ruleModal")closeRuleModal()};document.onkeydown=e=>{if(e.key==="Escape"){closeEmail();closeRuleModal()}};
});
`;
