export const DOMAINS_JS = `
let token = sessionStorage.getItem('vm_admin_token') || '';
let domainsCache = [];
let selectedDomain = '';
const $ = id => document.getElementById(id);
const ICONS={trash:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13M10 11v5M14 11v5"/></svg>',edit:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 20h4L19 9a2.8 2.8 0 0 0-4-4L4 16v4Z"/><path d="m13.5 6.5 4 4"/></svg>'};
function headers(extra){return Object.assign({Authorization:'Bearer '+token},extra||{})}
async function api(path,options){const o=options||{};const r=await fetch(path,Object.assign({},o,{headers:headers(o.headers||{})}));let d=null;try{d=await r.json()}catch(_){}if(r.status===401){sessionStorage.removeItem('vm_admin_token');token='';throw new Error('Unauthorized. Please return to Administration and sign in again.')}if(!r.ok)throw new Error(d&&d.error&&d.error.message||'Request failed');return d}
function show(text,error){const e=$('msg');e.textContent=text;e.className='notice show '+(error?'err':'ok')}
function modalShow(text,error){const e=$('domainMsg');e.textContent=text;e.className='notice show '+(error?'err':'ok')}
function loginShow(text){const e=$('loginMsg');e.textContent=text;e.className='notice show err'}
function esc(v){return String(v==null?'':v).split('&').join('&amp;').split('<').join('&lt;').split('>').join('&gt;').split('"').join('&quot;').split("'").join('&#039;')}
function iconButton(icon,title,cls,fn){const b=document.createElement('button');b.className='icon-btn '+(cls||'');b.title=title;b.setAttribute('aria-label',title);b.innerHTML=icon;b.onclick=fn;return b}
function renderDomain(d){const box=document.createElement('article');box.className='domain';const active=d.is_active;const head=document.createElement('div');head.className='domain-head';const info=document.createElement('div');info.innerHTML='<div class="domain-name">'+esc(d.domain)+'</div><div class="domain-summary"><span class="badge '+(active?'on':'off')+'"><span class="dot"></span>'+(active?'ACTIVE':'DISABLED')+'</span><span class="domain-count">'+d.destinations.length+' Gmail destination'+(d.destinations.length===1?'':'s')+'</span></div>';const edit=document.createElement('button');edit.type='button';edit.className='domain-edit';edit.innerHTML=ICONS.edit+'<span>Manage</span>';edit.onclick=()=>openDomainModal(d.domain);head.appendChild(info);head.appendChild(edit);box.appendChild(head);const note=document.createElement('div');note.className='domain-note';note.textContent='Mailbox login and sync support';box.appendChild(note);return box}
async function load(){try{const domains=await api('/admin/api/domains');domainsCache=domains||[];const list=$('list');list.innerHTML='';if(!domainsCache.length)list.innerHTML='<div class="empty">No domains configured.</div>';else domainsCache.forEach(d=>list.appendChild(renderDomain(d)));$('domainCount').textContent=domainsCache.length;$('activeCount').textContent=domainsCache.filter(d=>d.is_active).length;$('destinationCount').textContent=domainsCache.reduce((n,d)=>n+d.destinations.length,0)}catch(e){show(e.message||String(e),true)}}
function findDomain(domain){return domainsCache.find(d=>String(d.domain).toLowerCase()===String(domain).toLowerCase())}
function openDomainModal(domain){const d=findDomain(domain);if(!d)return;selectedDomain=d.domain;$('modalDomainName').textContent=d.domain;$('modalDomainStatus').textContent='Manage this domain without leaving the administration page.';$('domainMsg').className='notice';renderModal(d);$('domainModal').classList.add('show');$('modalDestinationInput').value='';}
function closeDomainModal(){$('domainModal').classList.remove('show');selectedDomain='';$('domainMsg').className='notice'}
function renderModal(d){const active=d.is_active;$('modalStatusBadge').innerHTML='<span class="badge '+(active?'on':'off')+'"><span class="dot"></span>'+(active?'ACTIVE':'DISABLED')+'</span>';$('toggleDomainBtn').className='btn '+(active?'danger':'success');$('toggleDomainBtn').textContent=active?'Disable Domain':'Enable Domain';$('modalDestinationCount').textContent=d.destinations.length+' configured';const list=$('modalDestinations');list.innerHTML='';if(!d.destinations.length){list.innerHTML='<div class="muted">No Gmail copy destinations configured.</div>';return}d.destinations.forEach(x=>{const row=document.createElement('div');row.className='dest';const left=document.createElement('div');left.className='dest-email';left.innerHTML=esc(x.destination_email)+' <span class="badge '+(x.is_active?'on':'off')+'">'+(x.is_active?'ACTIVE':'DISABLED')+'</span>';row.appendChild(left);const ra=document.createElement('div');ra.className='dest-actions';ra.appendChild(iconButton(ICONS.trash,'Remove destination','danger',()=>removeDestination(x.id)));row.appendChild(ra);list.appendChild(row)})}
async function openApp(){try{token=token.trim();if(!token)throw new Error('Please enter the admin token.');await api('/admin/api/domains');sessionStorage.setItem('vm_admin_token',token);$('login').classList.add('hidden');$('app').classList.remove('hidden');await load()}catch(e){sessionStorage.removeItem('vm_admin_token');token='';loginShow(e.message||'Invalid admin token.')}}
async function addDomain(){const domain=$('domain').value.trim(),destination=$('destination').value.trim();if(!domain)return show('Domain is required.',true);try{await api('/admin/api/domains',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({domain,destination_email:destination})});$('domain').value='';$('destination').value='';show('Domain added successfully.');await load()}catch(e){show(e.message,true)}}
async function toggleSelectedDomain(){const d=findDomain(selectedDomain);if(!d)return;const active=!d.is_active;try{await api('/admin/api/domains/'+encodeURIComponent(d.domain),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({is_active:active})});modalShow(active?'Domain enabled.':'Domain disabled.');await load();const fresh=findDomain(d.domain);if(fresh)renderModal(fresh)}catch(e){modalShow(e.message,true)}}
async function addDestination(){const input=$('modalDestinationInput');const destination=input.value.trim();if(!destination)return modalShow('Destination email is required.',true);try{await api('/admin/api/domains/'+encodeURIComponent(selectedDomain)+'/destinations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({destination_email:destination})});input.value='';await load();const fresh=findDomain(selectedDomain);if(fresh)renderModal(fresh);modalShow('Gmail destination added.')}catch(e){modalShow(e.message,true)}}
async function removeDestination(id){if(!confirm('Remove this Gmail copy destination?'))return;try{await api('/admin/api/destinations/'+encodeURIComponent(id),{method:'DELETE'});await load();const fresh=findDomain(selectedDomain);if(fresh)renderModal(fresh);modalShow('Gmail destination removed.')}catch(e){modalShow(e.message,true)}}
document.addEventListener('DOMContentLoaded',()=>{$('loginBtn').onclick=()=>{token=$('token').value.trim();openApp()};$('token').onkeydown=e=>{if(e.key==='Enter')$('loginBtn').click()};$('addBtn').onclick=addDomain;$('toggleDomainBtn').onclick=toggleSelectedDomain;$('modalAddDestination').onclick=addDestination;$('closeDomainBtn').onclick=closeDomainModal;$('domainModal').onclick=e=>{if(e.target.id==='domainModal')closeDomainModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDomainModal()});$('logoutBtn').onclick=()=>{sessionStorage.removeItem('vm_admin_token');token='';location.reload()};if(token)openApp()});
`;
