export const DOMAINS_JS = `
let token = sessionStorage.getItem('vm_admin_token') || '';
const $ = id => document.getElementById(id);
const ICONS={trash:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13M10 11v5M14 11v5"/></svg>'};
function headers(extra){return Object.assign({Authorization:'Bearer '+token},extra||{})}
async function api(path,options){const o=options||{};const r=await fetch(path,Object.assign({},o,{headers:headers(o.headers||{})}));let d=null;try{d=await r.json()}catch(_){}if(r.status===401)throw new Error('Unauthorized');if(!r.ok)throw new Error(d&&d.error&&d.error.message||'Request failed');return d}
function show(text,error){const e=$('msg');e.textContent=text;e.className='notice show '+(error?'err':'ok')}
function loginShow(text){const e=$('loginMsg');e.textContent=text;e.className='notice show err'}
function esc(v){return String(v==null?'':v).split('&').join('&amp;').split('<').join('&lt;').split('>').join('&gt;').split('"').join('&quot;').split("'").join('&#039;')}
function iconButton(icon,title,cls,fn){const b=document.createElement('button');b.className='icon-btn '+(cls||'');b.title=title;b.setAttribute('aria-label',title);b.innerHTML=icon;b.onclick=fn;return b}
function renderDomain(d){const box=document.createElement('article');box.className='domain';const active=d.is_active;const head=document.createElement('div');head.className='domain-head';const info=document.createElement('div');info.innerHTML='<div class="domain-name">'+esc(d.domain)+'</div><span class="badge '+(active?'on':'off')+'"><span class="dot"></span>'+(active?'ACTIVE':'DISABLED')+'</span><div class="muted" style="margin-top:7px">Mailbox login and sync support</div>';const actions=document.createElement('div');actions.className='actions';const toggle=document.createElement('button');toggle.className='btn small '+(active?'danger':'success');toggle.textContent=active?'Disable':'Enable';toggle.onclick=()=>toggleDomain(d.domain,!active);actions.appendChild(toggle);head.appendChild(info);head.appendChild(actions);box.appendChild(head);
const section=document.createElement('div');section.className='destinations';const title=document.createElement('div');title.className='dest-title';title.innerHTML='<strong>Gmail copy destinations</strong><span class="muted">'+d.destinations.length+' configured</span>';section.appendChild(title);if(!d.destinations.length){const empty=document.createElement('div');empty.className='muted';empty.textContent='No Gmail copy destinations configured.';section.appendChild(empty)}else d.destinations.forEach(x=>{const row=document.createElement('div');row.className='dest';const left=document.createElement('div');left.className='dest-email';left.innerHTML=esc(x.destination_email)+' <span class="badge '+(x.is_active?'on':'off')+'">'+(x.is_active?'ACTIVE':'DISABLED')+'</span>';row.appendChild(left);const ra=document.createElement('div');ra.className='dest-actions';ra.appendChild(iconButton(ICONS.trash,'Remove destination','danger',()=>removeDestination(x.id)));row.appendChild(ra);section.appendChild(row)});const add=document.createElement('div');add.className='add-destination';const input=document.createElement('input');input.placeholder='Add Gmail destination';const btn=document.createElement('button');btn.className='btn small';btn.textContent='Add Destination';btn.onclick=()=>addDestination(d.domain,input);add.appendChild(input);add.appendChild(btn);section.appendChild(add);box.appendChild(section);return box}
async function load(){try{const domains=await api('/admin/api/domains');const list=$('list');list.innerHTML='';if(!domains.length)list.innerHTML='<div class="empty">No domains configured.</div>';else domains.forEach(d=>list.appendChild(renderDomain(d)));$('domainCount').textContent=domains.length;$('activeCount').textContent=domains.filter(d=>d.is_active).length;$('destinationCount').textContent=domains.reduce((n,d)=>n+d.destinations.length,0)}catch(e){show(e.message||String(e),true)}}
async function openApp(){try{token=token.trim();await api('/admin/api/domains');sessionStorage.setItem('vm_admin_token',token);$('login').classList.add('hidden');$('app').classList.remove('hidden');await load()}catch(e){sessionStorage.removeItem('vm_admin_token');loginShow(e.message||'Invalid admin token.')}}
async function addDomain(){const domain=$('domain').value.trim(),destination=$('destination').value.trim();if(!domain)return show('Domain is required.',true);try{await api('/admin/api/domains',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({domain,destination_email:destination})});$('domain').value='';$('destination').value='';show('Domain added successfully.');await load()}catch(e){show(e.message,true)}}
async function toggleDomain(domain,active){try{await api('/admin/api/domains/'+encodeURIComponent(domain),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({is_active:active})});show(active?'Domain enabled.':'Domain disabled.');await load()}catch(e){show(e.message,true)}}
async function addDestination(domain,input){const destination=input.value.trim();if(!destination)return show('Destination email is required.',true);try{await api('/admin/api/domains/'+encodeURIComponent(domain)+'/destinations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({destination_email:destination})});show('Destination added.');await load()}catch(e){show(e.message,true)}}
async function removeDestination(id){if(!confirm('Remove this Gmail copy destination?'))return;try{await api('/admin/api/destinations/'+encodeURIComponent(id),{method:'DELETE'});show('Destination removed.');await load()}catch(e){show(e.message,true)}}
document.addEventListener('DOMContentLoaded',()=>{$('loginBtn').onclick=()=>{token=$('token').value.trim();openApp()};$('token').onkeydown=e=>{if(e.key==='Enter')$('loginBtn').click()};$('addBtn').onclick=addDomain;$('logoutBtn').onclick=()=>{sessionStorage.removeItem('vm_admin_token');location.reload()};if(token)openApp()});
`;
